### PR TITLE
Update CustomDatePickerIOS styling so it looks as close to the native UIActionSheet as possible

### PR DESCRIPTION
**Pull request by mars-lan**

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Hey @mars-lan, I can't test it right now, could you provide me a screenshot of this new improved style? (so I can merge this asap)

**Comment by mars-lan** [comment]
out

**Comment by mmazzarolo** [comment]
Thanks!

**Comment by mmazzarolo** [comment]
Landed in [v4.12.0](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v4.12.0).

**Pull request merged**
