### PR TITLE
[Discussion] Generic modal picker ?

### PR DESCRIPTION
**Pull request by eightyfive**
# Overview

While I was trying to write some `Picker` modal component from scratch, I was browsing your code, and it came to my attention that the `DateTimePickerModal.ios.js` component is very near from being a generic (iOS) "Modal Picker".

I did a few edits (see commit), tested locally, and it works like a charm. Main idea is to explicitly pass the `PickerComponent` in props.

Would you consider extracting this generic component into another repository? Or exporting it from this package?

PS: Feel free to ignore/close this PR, it serves more as a discussion material.

## Using with [`@react-native-community/datetimepicker`](https://github.com/react-native-community/react-native-datetimepicker)

```js
import PickerModal from "react-native-modal-datetime-picker";
import RNDateTimePicker from "@react-native-community/datetimepicker";

const DateTimePicker = ({onValueChange, ...rest}) => <RNDateTimePicker
    {...rest}
    onChange={(ev, date) => onValueChange(date)}
/>;

const Example = () => {
  // ...

  return (
    <View>
      <Button title="Show Date Picker" onPress={showDatePicker} />
      <PickerModal
        isVisible={isDatePickerVisible}
        mode="date"
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
        PickerComponent={DateTimePicker}
      />
    </View>
  );
};

export default Example;
```

## Using with official React Native [`Picker`](https://facebook.github.io/react-native/docs/picker)

```js
import { Picker as RNPicker } from "react-native";
import PickerModal from "react-native-modal-datetime-picker";

export default function Picker({ items, ...rest }) {
  return (
      <RNPicker {...rest}>
        {items.map(item=> (
          <RNPicker.Item {...{label: item, value: item, key: item }} />
        ))}
      </Picker>
  );
}

const Example = () => {
  // ...

  return (
    <View>
      <Button title="Show RN Picker" onPress={showDatePicker} />
      <PickerModal
        isVisible={isDatePickerVisible}
        mode="date"
        onConfirm={handleConfirm}
        onCancel={hideDatePicker}
        PickerComponent={Picker}
        items={['France', 'Canada', 'UK', ...]}
      />
    </View>
  );
};

export default Example;
```

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Hey @eightyfive , thanks for starting this discuss! 
I thought about it a couple of years ago, but at that time there was no "android" counterpart for a picker UI like this. Would it be meant to be used just on iOS? 

(FYI this is partially what I wanted to tackle with `react-native-dialog` 😬 )

**Comment by eightyfive** [comment]
Hey,

Yes, I think this is needed for iOS only, since android is already showing pickers as modal ([`datetimepicker`](https://github.com/react-native-community/react-native-datetimepicker) always as modal (correct me if I'm wrong) and standard [`Picker`](https://facebook.github.io/react-native/docs/picker) has a `mode='dialog'`).

So the idea is just to abstract this modal with the iOS styles mainly, so we can use it across more picker types.

BTW I believe `PickerSheetIOS` makes for a better name, since this looks more like an [`ActionSheetIOS`](https://facebook.github.io/react-native/docs/actionsheetios) to me.

Hope this helps, let me know.

**Comment by mmazzarolo** [comment]
> Yes, I think this is needed for iOS only, since android is already showing pickers as modal (datetimepicker always as modal (correct me if I'm wrong) and standard Picker has a mode='dialog').

That's correct. When I created this lib we didn't have the dialog mode for the picker on Android yet. 

> BTW I believe PickerSheetIOS makes for a better name, since this looks more like an ActionSheetIOS to me.

Unfortunately there are a bunch of terms related to the subject if we consider it a cross-platform component (Sheet/Dialog/Modal) but if we are strictly talking about iOS you're definitely right 👍 

I like your suggestion, and I think this is something that could definitely be helpful.  

From my point of view the process could be:  
- Extract the picker sheet "wrapper" modal in its own module (e.g. `PickerSheetIOS`). 
- Integrate `PickerSheetIOS` in `react-native-modal-datetime-picker`
- Optional: Create a cross-platform PickerModalDialogWhatever that exposes the same APIs on both Android and iOS. 

I'm pretty sure I should be able to tackle the first two steps during the christmas season (or first few days of Jan). 
Does it sound good to you?

**Comment by eightyfive** [comment]
Sounds awesome!

Ping me here if I can be of any help (I might have a shot at point 3 and share my findings here)

**Pull request closed without merging**
