### PR TITLE
Make minuteInterval work for iOS DateTimePicker

### PR DESCRIPTION
**Pull request by antoxann96**

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Hey! Thanks for the PR!
To me it's not totally clear tough, isn't passing the `minuteInterval` prop directly to the `DatePickerIOS` enough? 
Why is it kept in the state? 🤔

**Comment by antoxann96** [comment]
@mmazzarolo Unfortunately not, it is not enough. It works only this way because of some DatePickerIOS specific things. However, i don't think this fix broke anything in future. Just found it and think that probably it will be useful for others same as for me

**Comment by mmazzarolo** [comment]
Oh, ok, that's great! Thanks!

**Comment by mmazzarolo** [comment]
Landed in [v5.0.0](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v5.0.0)

**Comment by NarendraSingh88** [comment]
Is there any similar prop for this feature in Android?

**Comment by MssMaster** [comment]
I want to implement this feature in Android? Is it Possible?

**Pull request merged**
