### PR TITLE
feat: Add iOS 13 dark-mode support

### PR DESCRIPTION
**Pull request by mmazzarolo**
# Overview

Add iOS 13 dark-mode support

# Test Plan

See the updated README for the setup instructions. 
Fixes issue #283 
Related PRs: #286 #284

### CODE REVIEW

**Comment by mmazzarolo** [comment]
@RuslanShlinchak , @arjunnaha , @mohamedabusrea , @luisjimenezorozcoGL mind reviewing it? Thanks!

**Comment by RuslanShlinchak** [comment]
@mmazzarolo you distribute this changes?

**Comment by mmazzarolo** [comment]
Nope, but I think you can install it from here with:
`npm i mmazzarolo/react-native-modal-datetime-picker#pull/288/head`
or
`yarn add mmazzarolo/react-native-modal-datetime-picker#288/head`

More info [here](https://stackoverflow.com/questions/33181297/npm-install-from-github-pull-request)

**Pull request merged**
