### PR TITLE
upgraded momentjs to 2.19.0

### PR DESCRIPTION
**Pull request by patlux**
to fix react-native crash

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Thanks for the PR!
Merged, since it is only a dependency update. 
Could you tell me what kind of crash you're talking about?

**Comment by patlux** [comment]
https://github.com/moment/moment/pull/4187
https://github.com/moment/moment/pull/4213

**Comment by mmazzarolo** [comment]
Thank you :)

**Comment by mmazzarolo** [comment]
Landed in [v4.12.0](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v4.12.0).

**Pull request merged**
