### PR TITLE
minDateAndroid and maxDateAndroid converted minimumDate and maximumDate

### PR DESCRIPTION
**Pull request by geekvijay**

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Thank you @geekvijay, merged! 👍

**Comment by mmazzarolo** [comment]
Did you test it? Can I just publish it on npm? :)

**Comment by geekvijay** [comment]
i did it, You can push it to the npm :)

**Comment by mmazzarolo** [comment]
Just released it on npm, check for v3.0.0 👍

**Comment by geekvijay** [comment]
nice 👍

**Pull request merged**
