### PR TITLE
Avoid to override method onDateChange on iOS

### PR DESCRIPTION
**Pull request by fabiopaiva**
#134

### CODE REVIEW

**Comment by LucasMonteiro1** [comment]
Release date prediction?

**Comment by fabiopaiva** [comment]
No idea

**Comment by LucasMonteiro1** [comment]
Any ideia @mmazzarolo?

**Comment by mmazzarolo** [comment]
Ops.
Hey, tomorrow!

**Comment by mmazzarolo** [comment]
Landed in [v5.0.0](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v5.0.0)

**Pull request merged**
