### PR TITLE
We no longer allow a user to tap the confirm button unless picker = still.

### PR DESCRIPTION
**Pull request by SudoPlz**
TL/DR:
We no longer allow our user to tap the confirm button unless the picker is still.

Long version:
Up until now when the user interacted with the picker, if someone tapped on the confirm button, the state was not yet changed and thus the picked value would be old and miss-leading.
That's a bug of DatePickerIOS but since facebook doesn't do anything about it, I decided to created a workaround.

We no longer allow our user to tap the confirm button unless the picker is still.

They can always tap the cancel button anyway.

### CODE REVIEW

**Comment by mmazzarolo** [comment]
I like it, thank you :) 
Merged, I'll release it as soon as #39 gets merged. 
Could you also provide a link to the issue on the react-native repo? I'd like to link it in the comments.

**Comment by SudoPlz** [comment]
Not sure which one it was because I had a gazilion of tabs open, but it must be this one: https://github.com/facebook/react-native/issues/8169

**Comment by mmazzarolo** [comment]
Landed on [v4.6.0](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v4.6.0).  
Let me know if it works correctly.
I expanded a bit the comment and I also noticed that `userIsInteractingWithPicker` could also be removed from the state (but I left it there anyway).

**Comment by SudoPlz** [comment]
Thanks for that, but if you remove `userIsInteractingWithPicker` it will allow the confirm button to be pressed while the user is interacting with the picker and that's exactly what we're trying to avoid there..!
I'll try 4.6.0 on monday!

**Comment by mmazzarolo** [comment]
@SudoPlz 
Ops I didn't explain myself properly, my bad: `this.state.userIsInteractingWithPicker` can be moved from the state to `this.userIsInteractingWithPicker`, because it is an info that is not used in the `render`.

**Comment by SudoPlz** [comment]
yep.
No problem!

**Pull request merged**
