### PR TITLE
major: Force display to 'spinner' on iOS

### LINKED ISSUE #473: Issue with iOS 14
## Ask your Question

It seems your library is having issues with iOS 14 and is not quite working as expected. When my Xcode updated today to 12 and iOS 14, we no longer have a spinner available. I've tried using @react-native-community/datetimepicker's `display` prop to set it to `spinner` but to no avail, which may have something to do with this library using an older version of the datetimepicker library. Any help would be appreciated. 
Screen Shot 2020-09-18 at 4 57 15 PM

### PR DESCRIPTION
**Pull request by mmazzarolo**
BREAKING CHANGES.

Forces the `display` prop to `spinner` now that iOS14 defaults to a new component UI. 

Requires `@react-native-community/datetimepicker>13.0.0`

Fixes #473

### CODE REVIEW

**Comment by kyle-ssg** [comment]
Hey @mmazzarolo, I could be missing something however I don't see any difference after this update ? I can see that it forces display to spinner but the UI looks the same as before 
image

**Comment by mmazzarolo** [comment]
Make sure you update the community picker to 3.0.2

**Comment by kyle-ssg** [comment]
Yep it's using 3.0.2

**Comment by zstuder25** [comment]
Thanks! got this working. Just to clarify, you might have to run pod install again as well.

**Comment by daybreaker** [comment]
I'm on v9.0.0, and community date picker 3.0.2

I've deleted node_modules, and cleaned my cache. also run pod cache clean --all and reinstalled my pods.

But I'm still seeing this UI

**Comment by mmazzarolo** [comment]
@daybreaker does it work correctly if you use the community-picker directly?

**Comment by daybreaker** [comment]
Ah, nope. Even with display="spinner", the community date picker shows the new UI.

Looks like I'm headed over to their issue page! Thanks!

**Pull request merged**
