### PR TITLE
add README tip for setting locale in iOS

### PR DESCRIPTION
**Pull request by MacKentoch**
Hi @mmazzarolo 

Thank you for this library, Pretty handy 👍

I needed Datepicker to adapt on current locale. 24h format was not enough. 
So I add a tip in your README for those who like me may need Datepicker to adapt depending user locale.

Thank you

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Hey @MacKentoch ! Thanks a lot for the PR, merged! 👍

**Comment by luissmg** [comment]
@MacKentoch @mmazzarolo With this tip, should the buttons and title on the `Datepicker` also change without defining `cancelTextIOS`, `confirmTextIOS` and `titleIOS`? Because for me it does not work. Yes, it changes the 24h format and the days and months names, but not the buttons and title.

**Comment by MacKentoch** [comment]
@luissmg sorry but answer is no.

Any Date follow a predefined limited templates or rules so except difference from culture and language, this is adjustable.

But texts and labels or absolutely free to be set and languages are so wide in number.

`cancelTextIOS`, `confirmTextIOS ` can have React default properties but including i18n is way too much for this library and must stay dev responsability to use i18n if needed.

**Comment by luissmg** [comment]
Thanks for your reply and for your PR with this tip. I agree that adding `i18n` should not be added to this lib. Thanks once again for the quick reply! 👍

**Comment by gianpaj** [comment]
Thanks for these instructions.
Does Android need to be set up as well or will it know the current locale of the device?

**Pull request merged**
