### PR TITLE
Docs: Add Section with Solution for "double picker opening" bug

### PR DESCRIPTION
**Pull request by caiangums**
# Overview

Based on [the issue](https://github.com/react-native-datetimepicker/datetimepicker/issues/54) and the discussion, some approaches can be used. The most common approach is described at README with this PR.

# Test Plan

No Test needed! Just Docs update :smile:

### CODE REVIEW

**Review by mmazzarolo — APPROVED** [review]
Hey @caiangums , thanks for improving the docs 🙌 
Since the touchable + input part is not really related to the issue itself, can we mention only the part where we set the visibility to false first and then set the value? Or just linking the right answer in the thread would be cool too 👍

**Comment by caiangums** [comment]
@mmazzarolo Thanks for your quick review! Even tho the "bug" happens in Android, it is a common thing happening with the usage of `<Input />`. I can do something like this at the Readme:

<details><summary><strong>Example of solution using Input + DatePicker</strong></summary>
<p>
The most common approach for solving this when using an <code>Input</code> is:
<ul>
  <li>Wrap your <code>Input</code> with a "<code>Pressable</code>"/<code>Button</code> (<code>TouchableWithoutFeedback</code>/<code>TouchableOpacity</code> + <code>activeOpacity={1}</code> for example)</li>
  <li>Prevent <code>Input</code> from being focused. You could set <code>editable={false}</code> too for preventing Keyboard opening</li>
  <li>Triggering your <code>hideModal()</code> callback as a first thing inside <code>onConfirm</code>/<code>onCancel</code> callback props</li>
</ul>

```jsx
const [isVisible, setVisible] = useState(false);
const [date, setDate] = useState('');
<TouchableOpacity
  activeOpaticy={1}
  onPress={() => setVisible(true)}>
  <Input
    value={value}
    editable={false} // optional
  />
</TouchableOpacity>
<DatePicker
  isVisible={isVisible}
  onConfirm={(date) => {
    setVisible(false); // <- first thing
    setValue(parseDate(date)); 
  }}
  onCancel={() => setVisible(false)}
/>
```
</p>
</details>

**Comment by mmazzarolo** [comment]
Do you mean moving it into the accordion? sounds good 👍 
That said: the main thing I would add and highlight is that the source of the community picker bug is that, in Android, you should first hide the modal and then use/read the picked date (correct me if I'm wrong). 
The `input` example is fine, but as far as I know, the fact that it's involved in the discussion is because of a correlation, not causation.

**Comment by caiangums** [comment]
Makes total sense! I changed the description and linked the reply. I also added the example using `<Input />`. If I'm not clear with the description or something that I added just let me know and I can change it 😄 

Thanks for all your feedback and help! 😌

**Review by mmazzarolo — APPROVED** [review]
Looking good! 🙌 thanks for your contribution @caiangums :)

**Pull request merged**
