### PR TITLE
Fix - minuteInterval should take value from props

### PR DESCRIPTION
**Pull request by gbhasha**
while initializing the state for minuteInterval, Use the values passed from props, if undefined then use '1' as a fallback 

This fixes issue https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/158

### CODE REVIEW

**Comment by mmazzarolo** [comment]
@gbhasha you're basically fixing all the issues left on this repo. 
Thanks you so much 😀

**Comment by wildseansy** [comment]
This didn't fix it for me, it actually made it slightly worse. In v6.0.0 on iOS it renders the minuteInterval appropriately the first time the modal is presented. Subsequent presentations of the modal fail to respect the `minuteInterval` however.

I checked out this commit, hoping this would fix the issue above, but now the time picker doesn't respect `minuteInterval` altogether. Looking at the debugger, minuteInterval *is* getting properly passed to state, but for whatever reason, the minute interval is always 1 in the final render.

**Comment by mmazzarolo** [comment]
Thanks for reporting it @wildseansy, I'm reopening the issue . 
I'm on vacation at the moment so I can't test it (nor release it) but it seems weird indeed [if the render does not sync correctly to the state](https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=minuteInterval).  
Thank you for debugging it btw.

**Comment by ptboyer** [comment]
Just ran into this issue now also. Would be good to resolve this please! 😄

**Pull request merged**
