### PR TITLE
fix warn

### PR DESCRIPTION
**Pull request by ruamess**
-Delete DateTimePickerModal.defaultProps
-Add default props to arguments
-Rewrite areEqual function

# Test Plan

I'm only replace the default props value to arguments DateTimePickerModal component and change the areEqual function

### CODE REVIEW

**Review by huttonjd — APPROVED** [review]
I have tested changes and the warning goes away

**Comment by JosepHyv** [comment]
i hope this PR will be merged soon!, thank you so much!! ❤️

**Comment by GorillaWarHead** [comment]
@mmazzarolo can you merge this pls

**Comment by mmazzarolo** [comment]
Published! Thanks for the contribution and super sorry for the delay folks, just had another kid and I have basically 0 time to follow this repo 😅

**Pull request merged**
