### PR TITLE
update dependency react-native-modal

### PR DESCRIPTION
**Pull request by skb1129**

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Thank you!

**Comment by skb1129** [comment]
@mmazzarolo Can you please release this as a new version on NPM?

**Comment by mmazzarolo** [comment]
I'm away from my personal PC right now, I'll probably release it tomorrow. In the meanwhile you can target the master branch from your `package.json`.

**Comment by skb1129** [comment]
That'll be great. Thanks!

**Comment by mmazzarolo** [comment]
Published in `6.1.0`!

**Pull request merged**
