### PR TITLE
* fixed issue #283

### PR DESCRIPTION
**Pull request by RuslanShlinchak**
# Overview

# Test Plan

### CODE REVIEW

**Comment by mmazzarolo** [comment]
@RuslanShlinchak 👋 
Thanks for submitting the PR. I might be wrong here but isn't `react-native-appearance` a library that uses native code? 
Also, from [its documentation](https://github.com/expo/react-native-appearance#usage) it looks like it requires wrapping it in a provider. 
If that's the case I think it would be better to just expose a `darkMode` prop in `react-native-modal-datetime-picker` so that it can be toggled on/off externally without the need of adding the library here as a dependency.  
What do you think?

**Comment by RuslanShlinchak** [comment]
I think its good idea

пн, 23 сент. 2019 г. в 12:26, Matteo Mazzarolo <notifications@github.com>:

**Comment by RuslanShlinchak** [comment]
Not necessary wrapping it in a provider. We can use Appearance.getColorScheme() wrapper.
I think will be better use this module by default.

**Comment by mmazzarolo** [comment]
> I think will be better use this module by default.

The main problem I see here is that it requires native linking, and I'd prefer keeping this module just on the JS side if possible. Adding a native library as a direct dependency makes the module usage a bit more tricky (you need to link it) and it can cause issues if the user already uses the native library in the project for its own reasons. 
I would suggest one of the following approaches:
a. Expose a `darkMode` prop in `react-native-modal-datetime-picker` so that it can be toggled on/off externally without the need of adding additional libraries here as a dependency. Add documentation about the prop. 
*or*
b. Make `react-native-appearance` an optional dependency, use it only if available. Update the documentation explaining what is needed to install/link it. Once the feature lands in the next version of RN, remove `react-native-appearance` and update the doc.  

Opinions?  
(I can tackle the first one maybe tomorrow)

**Pull request closed without merging**
