### PR TITLE
docs: Update README.md

### PR DESCRIPTION
**Pull request by yurakruhlyk**
Hi, I updated the section about iOS dark mode, I found a new method with using useColorScheme hook from React-Native.

### CODE REVIEW

**Comment by mmazzarolo** [comment]
@yurakruhlyk thanks! 
I think your solution should be the "official" one (react-native-appearance is not used anymore since it's not delivered by RN). Mind removing the old one and just keep yours? (without the "if you use hooks").

**Comment by yurakruhlyk** [comment]
@mmazzarolo Done.

**Comment by mmazzarolo** [comment]
Thanks ❤️

**Pull request merged**
