### PR TITLE
Add spinner example

### PR DESCRIPTION
**Pull request by FDiskas**
# Overview

In some versions of community date picker the spinner mode was not working. So I added more examples to check if everything is working as aspected

https://github.com/react-native-community/datetimepicker/pull/118

### CODE REVIEW

**Comment by FDiskas** [comment]
Also removed yarn lock - because it locks `@react-native-community/datetimepicker` version. And in mane package `@react-native-community/datetimepicker` is peer dep. So example should always use latest version

**Comment by mmazzarolo** [comment]
@FDiskas , thanks for the PR. I updated the `@react-native-community/datetimepicker` version in the example's package. 
I'm not merging this PR though because I'd like to keep the example code simple, and the issue you had was related to the community version being outdated. 
Thanks for reporting !

**Comment by FDiskas** [comment]
Any way i thought that there should be as an example

**Comment by mmazzarolo** [comment]
> Any way i thought that there should be as an example

I'm avoiding it because it's an example of something that would be subject to changes that are not in our control (community picker changes)

**Pull request closed without merging**
