### PR TITLE
[typings] onHideAfterConfirm should be optional prop

### PR DESCRIPTION
**Pull request by iRoachie**

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Thank you! 👍 
Merged.

**Comment by iRoachie** [comment]
@mmazzarolo Dammmm that was fast :D

**Comment by mmazzarolo** [comment]
🥇

**Comment by iRoachie** [comment]
@mmazzarolo Forgot to push :D

**Comment by mmazzarolo** [comment]
My bad 🦆 
Landed on [v.4.8.0](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v4.8.0).

**Pull request merged**
