### PR TITLE
No safearea on IOS 

### PR DESCRIPTION
**Pull request by fahridev**
# Overview

  

# Test Plan

Screen Shot 2023-07-31 at 11 29 21

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Maybe I'm out of the loop here, but why do we need to put the `SafeAreaView` component inside this library? Can't you add it at the top level in your app instead?

**Comment by fahridev** [comment]
Since this error is only on the ios side, I applied it to this component. If we do it to other parties, I did it like this so that it wouldn't give a margin - padding error. @mmazzarolo

**Comment by thomasgallagher** [comment]
Same issue here, even though the component is nested in a SafeAreaProvider, it still shows outside of the safe area.

Screenshot 2023-08-09 at 22 14 28

**Comment by mmazzarolo** [comment]
Closed in favor of #718

**Pull request closed without merging**
