### PR TITLE
feat: Add cancelButtonTestID and confirmButtonTestID props for e2e te…

### PR DESCRIPTION
**Pull request by kanelloc**
Added support with e2e testing for 'submit' and 'cancel' buttons.

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Thank you @kanelloc , could you also update the README?

**Review by mmazzarolo — APPROVED** [review]

**Comment by kanelloc** [comment]
> Thank you @kanelloc , could you also update the README? 

Sure!!

**Comment by kanelloc** [comment]
@mmazzarolo I updated README with both props.

**Review by mmazzarolo — APPROVED** [review]
LGTM 👍 Thanks!

**Comment by dooleyb1** [comment]
@kanelloc Am I right in saying it is not currently possible to attach a `testID` to the confirm / cancel button of the `DateTimePicker` component for Android?

**Comment by kanelloc** [comment]
> @kanelloc Am I right in saying it is not currently possible to attach a `testID` to the confirm / cancel button of the `DateTimePicker` component for Android?

The above implementation is only for iOS.
I think you should go with a custom solution. For example pick the confirm/cancel buttons by text and then tap them.

**Pull request merged**
