### PR TITLE
Added typescript definitions

### LINKED ISSUE #36: Typescript typings
Interested in having typescript typings? For those using typescript with react native. I already started on it

### PR DESCRIPTION
**Pull request by iRoachie**
Resolves #36

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Thanks!

**Comment by iRoachie** [comment]
@mmazzarolo Don't forget to publish 👍

**Comment by mmazzarolo** [comment]
[Landed in v4.5.0 🐕 ](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v4.5.0)

**Comment by smriti-spotnana** [comment]
Can you show an example on how to use it with typescript? I tried did a couple things but, it's not working - 
```
import React from "react";
import DateTimePickerModal from "react-native-modal-datetime-picker/src";
import DateTimePicker from "react-native-modal-datetime-picker/typings";

export const DatePicker = (props: DateTimePicker): JSX.Element => <DateTimePickerModal mode="date" {...props} />;
```

**Comment by mmazzarolo** [comment]
@smriti-spotnana you don't have to import the types, they works automatically.
Also, you shouldn't import from `/src`, you should just do `import DateTimePickerModal from "react-native-modal-datetime-picker";`.  
The example should work with typescript as well.

**Comment by smriti-spotnana** [comment]
Thank you @mmazzarolo - was not expecting anyone to reply on my comment. 

- so, what do you mean by types will work automatically? If I don't import any types for props, then I will have to use `unknown` here. 
- This finally worked for me. Does this look correct to you? -
```
import { AndroidNativeProps, IOSNativeProps } from "@react-native-community/datetimepicker";
import React from "react";
import DateTimePickerModal, { DateTimePickerProps } from "react-native-modal-datetime-picker";

type IDateTimePickerProps = DateTimePickerProps &
  Omit<IOSNativeProps, "value" | "mode"> &
  Omit<AndroidNativeProps, "value" | "mode">;

export const TimePicker = (props: IDateTimePickerProps): JSX.Element => <DateTimePickerModal mode="time" {...props} />;
```

**Comment by mmazzarolo** [comment]
Ah! Now I get what you mean, you want to use the component props in your own component. It wasn't clear to me, I thought you meant that the types didn't work at all. 
I think there are 3 solutions here:
1. Send a PR to export the types
2. Use your current approach
3. Extract the props [in a more elegant way](https://stackoverflow.com/a/55005902)

**Comment by smriti-spotnana** [comment]
THANK YOU :D 
 - Updated my code with 3) approach, and sending a PR to export types :) 
```
import React from "react";
import DateTimePickerModal from "react-native-modal-datetime-picker";

type IDateTimePickerProps = React.ComponentProps<typeof DateTimePickerModal>;

export const TimePicker = (props: IDateTimePickerProps): JSX.Element => <DateTimePickerModal mode="time" {...props} />;
```

**Pull request merged**
