### PR TITLE
Removed isDarkModeEnabled prop and formatting

### PR DESCRIPTION
**Pull request by mmazzarolo**
# Overview

# Test Plan

### CODE REVIEW

**Comment by mikehardy** [comment]
This is definitely a semver breaking change!
Please note I contribute very heavily to open source and I'm using this package which I'm not maintaining (thank you! seriously) so I'm not really complaining, but semver breaks are worth noting

**Comment by mmazzarolo** [comment]
Ouch! Thanks @mikehardy , you are 100% right, I was trying to release from mobile and did a mess. Any suggestion on how we can make improve the current state?

**Comment by mikehardy** [comment]
I'd just bump it again and say "sorry folks :-), use <previous package version> if you are not ready for the break yet", that's what I've done in the past when I've accidentally semver-violated

**Pull request merged**
